language: swift
xcode_workspace: RSDKUtils.xcworkspace
xcode_scheme: Tests
osx_image: xcode10.3

before_install:
- bundle install
- gem update fastlane cocoapods --no-document
- travis_wait pod repo update

script:
- fastlane ci
