# Import base_config from git
import_from_git(url: 'https://github.com/rakutentech/ios-buildconfig.git')

default_platform(:ios)

platform :ios do
  desc "Build everything"
  lane :ci do |options|
    tests(options)
    coverage
  end

  desc "Run tests"
  lane :tests do
    build_swift_package # running before .xcworkspace is created
    cocoapods(repo_update: ENV['REM_FL_CP_REPO_UPDATE'] || false)

    scan(
      clean: true,
      skip_build: true,
      output_directory: './artifacts/unit-tests',
      scheme: ENV['REM_FL_TESTS_SCHEME'] || 'Tests',
      device: ENV['REM_FL_TESTS_DEVICE'] || 'REM SDK Unit Tests',
      code_coverage: true,
      output_types: 'json-compilation-database,html,junit',
      output_files: 'compile_commands.json,report.html,report.junit')

    lint_module
  end

  desc "Generate code coverage"
  lane :coverage do |options|
    slather(
      output_directory: './artifacts/coverage',
      scheme: ENV['REM_FL_TESTS_SCHEME'] || 'Tests',
      sonarqube_xml: true,
      use_bundle_exec: true,
      proj: ENV['REM_FL_TESTS_PROJECT'],
      workspace: ENV['REM_FL_TESTS_WORKSPACE'],
      binary_basename: ENV['REM_FL_TESTS_SLATHER_BASENAME'],
      ignore: '*.{h,m}')
  end

  lane :build_swift_package do
    xcodebuild(
      clean: true,
      build: true,
      scheme: 'RSDKUtilsMain',
      destination: 'platform=iOS Simulator,name=' + ENV['REM_FL_TESTS_DEVICE'] || 'iPhone 11',
      xcargs: '"APPLICATION_EXTENSION_API_ONLY=YES"'
    )
    xcodebuild(
      clean: true,
      build: true,
      scheme: 'RSDKUtilsMain',
      destination: 'platform=watchOS Simulator,name=Apple Watch Series 6 - 40mm'
    )
    xcodebuild(
      clean: true,
      build: true,
      scheme: 'RSDKUtilsNimble',
      destination: 'platform=iOS Simulator,name=' + ENV['REM_FL_TESTS_DEVICE'] || 'iPhone 11'
    )
    xcodebuild(
      clean: true,
      build: true,
      scheme: 'RSDKUtilsTestHelpers',
      destination: 'platform=iOS Simulator,name=' + ENV['REM_FL_TESTS_DEVICE'] || 'iPhone 11'
    )
  end
end
# vim:syntax=ruby:et:sts=2:sw=2:ts=2:ff=unix:
