# Import base_config from git
import_from_git(url: 'https://github.com/rakutentech/ios-buildconfig.git')

default_platform(:ios)

platform :ios do
  desc "Build everything"
  lane :ci do |options|
    tests(options)
    coverage
  end

  desc "Run tests"
  lane :tests do
    build_swift_package # running before .xcworkspace is created
    cocoapods(repo_update: ENV['REM_FL_CP_REPO_UPDATE'] || false)

    scan(
      clean: true,
      skip_build: true,
      output_directory: './artifacts/unit-tests',
      scheme: ENV['REM_FL_TESTS_SCHEME'] || 'Tests',
      device: ENV['REM_FL_TESTS_DEVICE'] || 'iPhone 11',
      code_coverage: true,
      xcodebuild_formatter: 'xcpretty',
      output_types: 'json-compilation-database,html,junit',
      output_files: 'compile_commands.json,report.html,report.junit')

    lint_module
  end

  desc "Generate code coverage"
  lane :coverage do |options|
    slather(
      output_directory: './artifacts/coverage',
      scheme: ENV['REM_FL_TESTS_SCHEME'] || 'Tests',
      sonarqube_xml: true,
      use_bundle_exec: true,
      proj: ENV['REM_FL_TESTS_PROJECT'],
      workspace: ENV['REM_FL_TESTS_WORKSPACE'],
      binary_basename: ENV['REM_FL_TESTS_SLATHER_BASENAME'],
      ignore: '*.{h,m}')
  end

  lane :build_swift_package do
    ios_destination = 'platform=iOS Simulator,name=' + ENV['REM_FL_TESTS_DEVICE'] || 'iPhone 11'
    watchos_destination = 'platform=watchOS Simulator,name=Apple Watch Series 6 - 40mm'

    Build = Struct.new(:scheme, :destination, :xcargs)
    main_build_ios = Build.new('RSDKUtilsMain', ios_destination, '"APPLICATION_EXTENSION_API_ONLY=YES"')
    main_build_watchos = Build.new('RSDKUtilsMain', watchos_destination)
    nimble_build_ios = Build.new('RSDKUtilsNimble', ios_destination)
    helpers_build_ios = Build.new('RSDKUtilsTestHelpers', ios_destination)

    [main_build_ios, main_build_watchos, nimble_build_ios, helpers_build_ios].each do |build|
      xcodebuild(
        clean: true,
        build: true,
        scheme: build.scheme,
        destination: build.destination,
        xcargs: build.xcargs
      )
    end
  end
end
# vim:syntax=ruby:et:sts=2:sw=2:ts=2:ff=unix:
