name: Build and Test

on:
  pull_request_target:

permissions:
  checks: write

jobs:
  build-test:
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - run: |
          bundle install
          bundle exec pod install
          xcodebuild \
          -workspace RSDKUtils.xcworkspace \
          -scheme Tests \
          -resultBundlePath artifacts/unit-tests/Tests \
          -destination "platform=iOS Simulator,name=iPhone 11" \
          test
      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: |
            artifacts/unit-tests/Tests.xcresult
          upload-bundles: false
        if: success() || failure()
